### Merits of using numpy

#### Initialising
- importing wanted libraries.
- initialise some matrices.

In [128]:
import numpy as np
import time as time
mat_1=[[1,5,9,7,5,6,8],[4,9,2,7,7,6,3],[11,2,5,14,5,6,5],[8,4,23,5,1,6,7],[9,15,4,7,13,6,9],[18,5,7,6,17,4,0],[4,6,1,5,3,8,9]]
mat_2=np.random.randint(10, size=(7,7))
array_1=np.array(mat_1)
add=np.zeros((7,7))
multiply=np.zeros((7,7))

#### Creating functions
- addition and multiplication using simple element by element loop.
- inverse using row operations according to jordan elimination method

In [129]:
def Matrixadd(A,B):
    for i in range(len(A)):
        for j in range(len(A)):
            add[i][j] = A[i][j] + B[i][j]
    return print(add)

def Matrixmultiply(A, B):
    for i in range(len(A)):
        for j in range(len(A)):
            for k in range(len(B)):
                multiply[i][j] = multiply[i][j] + A[i][k] * B[k][j]
    return print(multiply)

def invert_matrix(A):
    n = len(A)
    I=np.identity(n) #creates a identity matrix of order n
    index = list(range(n))
    for fd in range(n):
        diagScaler = 1.0 / A[fd][fd] 
        for j in range(n):
            A[fd][j] *= diagScaler
            I[fd][j] *= diagScaler
        for i in index[0:fd] + index[fd+1:]: 
            ro_op = A[i][fd]
            for j in range(n): 
                A[i][j] = A[i][j] - ro_op * A[fd][j]
                I[i][j] = I[i][j] - ro_op * I[fd][j]
    return print(I)

#### Addition

In [130]:
start=time.time()
Matrixadd(mat_1, mat_2)
end=time.time()
print("time taken for function ", end-start)

start=time.time()
nadd=np.add(mat_1,mat_2)
print(nadd)
end=time.time()
print("time taken for library ", end-start)


[[ 7.  5. 14.  7.  8. 12. 15.]
 [10. 12.  2. 11. 11. 14.  5.]
 [19. 11.  7. 21.  7. 15. 14.]
 [11. 12. 26. 10.  1. 14. 11.]
 [10. 17. 10. 11. 16.  7. 16.]
 [26.  6. 13.  8. 22.  6.  7.]
 [13. 11.  1.  7.  9. 10. 16.]]
time taken for function  0.0014967918395996094
[[ 7  5 14  7  8 12 15]
 [10 12  2 11 11 14  5]
 [19 11  7 21  7 15 14]
 [11 12 26 10  1 14 11]
 [10 17 10 11 16  7 16]
 [26  6 13  8 22  6  7]
 [13 11  1  7  9 10 16]]
time taken for library  0.0017940998077392578


#### Multiplication

In [131]:
start=time.time()
Matrixmultiply(mat_1,mat_2)
end=time.time()
print("time taken for function ", end-start)

start=time.time()
nmultiply=np.matmul(mat_1,mat_2)
print(nmultiply)
end=time.time()
print("time taken for library", end-start)

[[254. 208. 110. 166. 134. 216. 259.]
 [197. 136. 123. 131. 121. 195. 204.]
 [258. 204. 173. 155. 126. 266. 294.]
 [383. 302. 143. 232. 161. 354. 389.]
 [339. 214. 188. 205. 218. 309. 353.]
 [261. 164. 248. 175. 159. 284. 370.]
 [231. 126. 103. 102. 141. 158. 209.]]
time taken for function  0.0020241737365722656
[[254 208 110 166 134 216 259]
 [197 136 123 131 121 195 204]
 [258 204 173 155 126 266 294]
 [383 302 143 232 161 354 389]
 [339 214 188 205 218 309 353]
 [261 164 248 175 159 284 370]
 [231 126 103 102 141 158 209]]
time taken for library 0.0009770393371582031


#### Inversion

In [132]:
start=time.time()
ninv=np.linalg.inv(array_1)
end=time.time()
print(ninv,"\n")


start1=time.time()
invert_matrix(mat_1)
end1=time.time()
print("time taken for function ", end1-start1)
print("time taken for library ", end-start)

[[-0.12330186 -0.04568525  0.03569765  0.03395273  0.0338962   0.00877247
   0.04469416]
 [-0.10111693  0.08394107 -0.00404459  0.03897706  0.07572191 -0.05643968
  -0.04188905]
 [ 0.03069085  0.01110206 -0.01592277  0.03638299 -0.00886035  0.00305681
  -0.04157299]
 [ 0.03186163  0.02728869  0.09092117 -0.02054254  0.01557226 -0.04260348
  -0.08752416]
 [ 0.13677146 -0.02888301 -0.04347903 -0.05715412 -0.01976312  0.06591297
  -0.02357562]
 [-0.00152562  0.16304843 -0.0793147   0.00853996 -0.17104479  0.05949918
   0.15547294]
 [ 0.05686673 -0.18735437  0.02308318 -0.02224455  0.0854145  -0.01780261
   0.04207719]] 

[[-0.12330186 -0.04568525  0.03569765  0.03395273  0.0338962   0.00877247
   0.04469416]
 [-0.10111693  0.08394107 -0.00404459  0.03897706  0.07572191 -0.05643968
  -0.04188905]
 [ 0.03069085  0.01110206 -0.01592277  0.03638299 -0.00886035  0.00305681
  -0.04157299]
 [ 0.03186163  0.02728869  0.09092117 -0.02054254  0.01557226 -0.04260348
  -0.08752416]
 [ 0.13677146 -0.0