# Assignment 1
---

### Defining a function which give a m n matrix
---

In [450]:
def mat(n,m):
    return [random.choices(range(0,10),k=m) for _ in range(n)]

In [451]:
import time as tm

---
### Matrix Addition
___


In [452]:
t1=tm.time()

In [453]:
matA=list(mat(5,6))
matA


[[7, 2, 5, 8, 8, 3],
 [9, 7, 6, 1, 0, 8],
 [3, 9, 8, 2, 1, 1],
 [7, 1, 8, 5, 9, 8],
 [6, 8, 2, 5, 2, 4]]

In [454]:
matB=list(mat(5,6))
matB

[[5, 2, 2, 9, 7, 0],
 [5, 1, 3, 4, 3, 3],
 [8, 6, 8, 2, 4, 7],
 [2, 7, 6, 4, 3, 0],
 [6, 8, 1, 9, 0, 7]]

In [455]:
def mat_add(matA,matB):
    return[ [matA[i1][j1] + matB[i1][j1] for j1 in range(len(matA[0]))] for i1 in range(len(matA))]

In [456]:
mat_add(matA,matB)

[[12, 4, 7, 17, 15, 3],
 [14, 8, 9, 5, 3, 11],
 [11, 15, 16, 4, 5, 8],
 [9, 8, 14, 9, 12, 8],
 [12, 16, 3, 14, 2, 11]]

In [457]:
t2=tm.time()
t2-t1

0.17962312698364258

---
### Matrix Multiplication
---

In [458]:
t3=tm.time()

In [459]:
#For Multiplication we want p q and q r type matrix
matC=mat(3,4)
matD=mat(4,6)
print(matC)
print(matD)

[[4, 8, 7, 3], [2, 0, 6, 0], [9, 4, 6, 0]]
[[4, 7, 7, 9, 2, 8], [9, 4, 8, 6, 8, 2], [3, 1, 2, 1, 2, 5], [4, 3, 7, 4, 5, 7]]


In [460]:
def sub(matC,m,matD,n):
    element=0
    for i in range(len(matC[0])):
        element = element + (matC[m][i])* (matD[i][n])
    return element

In [461]:
[[  sub(matC,i,matD,j) for i in range(len(matC))] for j in range(len(matD[0]))]

[[121, 26, 90],
 [76, 20, 85],
 [127, 26, 107],
 [103, 24, 111],
 [101, 16, 62],
 [104, 46, 110]]

In [462]:
t4=tm.time()
t4-t3

0.1177980899810791

---
### Inverse of a Matrix
---

In [463]:
MatInverse=mat(3,3)

In [464]:
def transposeMatrix(m):
    return map(list,zip(*m))

In [465]:
def getMatrixMinor(m,i,j):
    return [row[:j] + row[j+1:] for row in (m[:i]+m[i+1:])]

In [466]:
def getMatrixDeterminant(m):
     #base case for 2x2 matrix
     if len(m) == 2:
         return m[0][0]*m[1][1]-m[0][1]*m[1][0]

     determinant = 0
     for c in range(len(m)):
         determinant += ((-1)**c)*m[0][c]*getMatrixDeterminant(getMatrixMinor(m,0,c))
     return determinant

In [467]:
def getMatrixInverse(m):
     determinant = getMatrixDeterminant(m)
    #special case for 2x2 matrix:
     if len(m) == 2:
         return [[m[1][1]/determinant, -1*m[0][1]/determinant],[-1*m[1][0]/determinant, m[0][0]/determinant]]

     #find matrix of cofactors
     cofactors = []
     for r in range(len(m)):
         cofactorRow = []
         for c in range(len(m)):
             minor = getMatrixMinor(m,r,c)
             cofactorRow.append(((-1)**(r+c)) * getMatrixDeterminant(minor))
         cofactors.append(cofactorRow)
     cofactors = transposeMatrix(cofactors)
     for r in range(len(m)):
         for c in range(len(m)):
             cofactors[r][c] = cofactors[r][c]/determinant
     return cofactors

In [468]:
#getMatrixInverse(MatInverse)

---
# By Using Numpy
---

In [469]:
import numpy as np

In [470]:
t1=tm.time()

---
### Addition through Numpy
---

In [471]:
a=np.array(mat(2,3))
a

array([[2, 9, 6],
       [6, 2, 4]])

In [472]:
b=np.array(mat(2,3))
b

array([[0, 6, 1],
       [8, 2, 2]])

In [473]:
np.add(a,b)

array([[ 2, 15,  7],
       [14,  4,  6]])

In [474]:
t2=tm.time()
t2-t1

0.1116018295288086

---
### Multiplication through Numpy
---

In [475]:
a=np.array(mat(4,5))
a

array([[8, 5, 7, 2, 0],
       [0, 5, 2, 6, 7],
       [2, 9, 7, 7, 0],
       [8, 8, 0, 7, 7]])

In [476]:
b=np.array(mat(5,8))
b

array([[9, 7, 8, 9, 5, 8, 3, 4],
       [7, 6, 9, 2, 4, 9, 8, 8],
       [4, 6, 9, 2, 9, 2, 7, 4],
       [8, 2, 6, 9, 2, 5, 2, 5],
       [2, 7, 7, 8, 2, 9, 6, 9]])

In [477]:
np.dot(a,b)

array([[151, 132, 184, 114, 127, 133, 117, 110],
       [105, 103, 148, 124,  64, 142, 108, 141],
       [165, 124, 202, 113, 123, 146, 141, 143],
       [198, 167, 227, 207, 100, 234, 144, 194]])

In [478]:
t3=tm.time()
t3-t2

0.10338521003723145

---
### Inverse through Numpy
---

In [479]:
c=mat(6,6)
c

[[5, 7, 7, 0, 8, 6],
 [4, 9, 1, 4, 9, 7],
 [1, 7, 6, 8, 5, 2],
 [2, 2, 8, 9, 0, 5],
 [5, 6, 5, 2, 0, 7],
 [6, 8, 9, 0, 6, 0]]

In [480]:
np.linalg.inv(c)

array([[-0.27809135,  0.27023688, -0.37695795,  0.23549813, -0.09238354,
         0.27956477],
       [-0.01026862, -0.08429106,  0.22805168, -0.20380823,  0.17351241,
        -0.04991499],
       [ 0.14738751, -0.15439193,  0.09096679, -0.01509691,  0.01285277,
        -0.04073444],
       [-0.14702482,  0.12094526, -0.06259776,  0.1282557 , -0.06865012,
         0.06678001],
       [ 0.07070158,  0.07373909, -0.06356115,  0.05889153, -0.15824549,
         0.01475689],
       [ 0.14416865, -0.0450527 ,  0.0266916 , -0.01938116,  0.07055423,
        -0.14688881]])

In [481]:
t4=tm.time()
t4-t3

0.07819080352783203

---
---
---
---