To import the required libraries

In [10]:
import numpy as np
import random
import time

to input the size of the matrix

In [11]:
n=input("Enter size of square matrix")
n=int(n)

Enter size of square matrix3


In [12]:
array1=[[random.random() for i in range(n)] for j in range(n)]
array2=[[random.random() for i in range(n)] for j in range(n)]

to print the first array

In [13]:
print("First array")
for e in array1:
    print(e)

First array
[0.23665119734301454, 0.6630408199692481, 0.5825454035661572]
[0.015188014568703334, 0.601078277779338, 0.01472641322775281]
[0.6169037085257068, 0.7647323728470248, 0.9478357828631212]


to print the second array

In [14]:
print("Second array")
for e in array2:
    print(e)

Second array
[0.21610524896975025, 0.43116722042752276, 0.6352271391585872]
[0.3055285014673803, 0.6779492886822429, 0.6253346745281133]
[0.19610434896790918, 0.002708924537384916, 0.5527278252955774]


To compute their product

In [15]:
start = time.process_time()
productmat=np.zeros((n,n))
for i in range(len(array1)):
    #iterate through columns of array1
    for j in range(len(array2[0])):
        # iterate through rows of array2
        for k in range(len(array2)):
           productmat[i][j] += array1[i][k] * array2[k][j]

To print thier product now

In [16]:
print("Their product")
for r in productmat:
    print(r)
print(time.process_time() - start)

Their product
[0.36795912 0.55312236 0.88693873]
[0.18981667 0.41408906 0.39366263]
[0.55283838 0.78700604 1.39398286]
0.010054999999999925


Now let's head on to the addition part

In [17]:
start1 = time.process_time()
summat=np.zeros((n,n))
for i in range(n):
    for j in range(n):
        summat[i][j]=array1[i][j] + array2[i][j]


Now printing

In [18]:
print("Their sum")
for r in summat:
    print(r)
print(time.process_time() - start1)

Their sum
[0.45275645 1.09420804 1.21777254]
[0.32071652 1.27902757 0.64006109]
[0.81300806 0.7674413  1.50056361]
0.01105199999999984


Now the inverse part

In [19]:
start2 = time.process_time()
def print_matrix(Title, M):
    print(Title)
    for row in M:
        print([round(x,3)+0 for x in row])
        
def print_matrices(Action, Title1, M1, Title2, M2):
    print(Action)
    print(Title1, '\t'*int(len(M1)/2)+"\t"*len(M1), Title2)
    for i in range(len(M1)):
        row1 = ['{0:+7.3f}'.format(x) for x in M1[i]]
        row2 = ['{0:+7.3f}'.format(x) for x in M2[i]]
        print(row1,'\t', row2)
        
def zeros_matrix(rows, cols):
    A = []
    for i in range(rows):
        A.append([])
        for j in range(cols):
            A[-1].append(0.0)

    return A

def copy_matrix(M):
    rows = len(M)
    cols = len(M[0])

    MC = zeros_matrix(rows, cols)

    for i in range(rows):
        for j in range(rows):
            MC[i][j] = M[i][j]

    return MC

def matrix_multiply(A,B):
    rowsA = len(A)
    colsA = len(A[0])

    rowsB = len(B)
    colsB = len(B[0])

    if colsA != rowsB:
        print('Number of A columns must equal number of B rows.')
        sys.exit()

    C = zeros_matrix(rowsA, colsB)

    for i in range(rowsA):
        for j in range(colsB):
            total = 0
            for ii in range(colsA):
                total += A[i][ii] * B[ii][j]
            C[i][j] = total

    return C

In [20]:
A = array1
I = [[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,0,1]]
print_matrix('A Matrix', A)
print()
print_matrix('I Matrix', I)

A Matrix
[0.237, 0.663, 0.583]
[0.015, 0.601, 0.015]
[0.617, 0.765, 0.948]

I Matrix
[1, 0, 0, 0, 0]
[0, 1, 0, 0, 0]
[0, 0, 1, 0, 0]
[0, 0, 0, 1, 0]
[0, 0, 0, 0, 1]


In [21]:
AM = copy_matrix(A)
IM = copy_matrix(I)
n = len(AM)

exString = """
Since the matrices won't be the original A and I as we start row operations, 
    the matrices will be called: AM for "A Morphing", and IM for "I Morphing" 
"""
print(exString)
print_matrix('AM Matrix', AM)
print()
print_matrix('IM Matrix', IM)


Since the matrices won't be the original A and I as we start row operations, 
    the matrices will be called: AM for "A Morphing", and IM for "I Morphing" 

AM Matrix
[0.237, 0.663, 0.583]
[0.015, 0.601, 0.015]
[0.617, 0.765, 0.948]

IM Matrix
[1, 0, 0, 0, 0]
[0, 1, 0, 0, 0]
[0, 0, 1, 0, 0]
[0, 0, 0, 1, 0]
[0, 0, 0, 0, 1]


In [22]:
fd = 0 # fd stands for focus diagonal
fdScaler = 1. / AM[fd][fd]

for j in range(n): # using j to indicate cycling through columns
    AM[fd][j] = fdScaler * AM[fd][j]
    IM[fd][j] = fdScaler * IM[fd][j]

print_matrix('AM Matrix', AM)
print()
print_matrix('IM Matrix', IM)

AM Matrix
[1.0, 2.802, 2.462]
[0.015, 0.601, 0.015]
[0.617, 0.765, 0.948]

IM Matrix
[4.226, 0.0, 0.0, 0, 0]
[0, 1, 0, 0, 0]
[0, 0, 1, 0, 0]
[0, 0, 0, 1, 0]
[0, 0, 0, 0, 1]


In [23]:
n = len(A)
indices = list(range(n))

for i in indices[0:fd] + indices[fd+1:]: # *** skip row with fd in it.
    crScaler = AM[i][fd] # cr stands for "current row".
    for j in range(n): # cr - crScaler * fdRow, but one element at a time.
        AM[i][j] = AM[i][j] - crScaler * AM[fd][j]
        IM[i][j] = IM[i][j] - crScaler * IM[fd][j]
    
print_matrix('AM Matrix', AM)
print()
print_matrix('IM Matrix', IM)

AM Matrix
[1.0, 2.802, 2.462]
[0.0, 0.559, -0.023]
[0.0, -0.964, -0.571]

IM Matrix
[4.226, 0.0, 0.0, 0, 0]
[-0.064, 1.0, 0.0, 0, 0]
[-2.607, 0.0, 1.0, 0, 0]
[0, 0, 0, 1, 0]
[0, 0, 0, 0, 1]


In [24]:
indices = list(range(n)) # to allow flexible row referencing ***
# We've already run for fd = 0, now let's run for fd = 1 to the last fd
for fd in range(1,n): # fd stands for focus diagonal
    fdScaler = 1.0 / AM[fd][fd]
    # FIRST: scale fd row with fd inverse. 
    for j in range(n): # Use j to indicate column looping.
        AM[fd][j] *= fdScaler
        IM[fd][j] *= fdScaler
    
    # Section to print out current actions:
    string1 = '\nUsing the matrices above, Scale row-{} of AM and IM by '
    string2 = 'diagonal element {} of AM, which is 1/{:+.3f}.\n'
    stringsum = string1 + string2
    val1 = fd+1; val2 = fd+1
    Action = stringsum.format(val1,val2,round(1./fdScaler,3))
    print(Action)
    print_matrix('AM Matrix', AM)
    print()
    print_matrix('IM Matrix', IM)
    print()
    
    # SECOND: operate on all rows except fd row.
    for i in indices[:fd] + indices[fd+1:]: # *** skip row with fd in it.
        crScaler = AM[i][fd] # cr stands for "current row".
        for j in range(n): # cr - crScaler * fdRow, but one element at a time.
            AM[i][j] = AM[i][j] - crScaler * AM[fd][j]
            IM[i][j] = IM[i][j] - crScaler * IM[fd][j]
        
        # Section to print out current actions:
        string1 = 'Using the matrices above, subtract {:+.3f} * row-{} of AM from row-{} of AM, and \n'
        string2 = '\tsubtract {:+.3f} * row-{} of IM from row-{} of IM\n'
        val1 = i+1; val2 = fd+1
        stringsum = string1 + string2
        Action = stringsum.format(crScaler, val2, val1, crScaler, val2, val1)
        print(Action)
        print_matrix('AM Matrix', AM)
        print()
        print_matrix('IM Matrix', IM)
        print()
    print(time.process_time() - start2)


Using the matrices above, Scale row-2 of AM and IM by diagonal element 2 of AM, which is 1/+0.559.

AM Matrix
[1.0, 2.802, 2.462]
[0.0, 1.0, -0.041]
[0.0, -0.964, -0.571]

IM Matrix
[4.226, 0.0, 0.0, 0, 0]
[-0.115, 1.79, 0.0, 0, 0]
[-2.607, 0.0, 1.0, 0, 0]
[0, 0, 0, 1, 0]
[0, 0, 0, 0, 1]

Using the matrices above, subtract +2.802 * row-2 of AM from row-1 of AM, and 
	subtract +2.802 * row-2 of IM from row-1 of IM

AM Matrix
[1.0, 0.0, 2.575]
[0.0, 1.0, -0.041]
[0.0, -0.964, -0.571]

IM Matrix
[4.548, -5.016, 0.0, 0, 0]
[-0.115, 1.79, 0.0, 0, 0]
[-2.607, 0.0, 1.0, 0, 0]
[0, 0, 0, 1, 0]
[0, 0, 0, 0, 1]

Using the matrices above, subtract -0.964 * row-2 of AM from row-3 of AM, and 
	subtract -0.964 * row-2 of IM from row-3 of IM

AM Matrix
[1.0, 0.0, 2.575]
[0.0, 1.0, -0.041]
[0.0, 0.0, -0.61]

IM Matrix
[4.548, -5.016, 0.0, 0, 0]
[-0.115, 1.79, 0.0, 0, 0]
[-2.718, 1.725, 1.0, 0, 0]
[0, 0, 0, 1, 0]
[0, 0, 0, 0, 1]

0.08070199999999983

Using the matrices above, Scale row-3 of AM and IM b

END.. Created by- Harshit Chaudhary 210421