## Checking the time taken by numpy library and loops

#### Initializing matrices and importing modules
- importing time and numpy module for time calculation and matrix operations respectively.

In [326]:
import time as T
import numpy as np
raw_1=[[1,5,9,7,5,6],[4,9,2,7,7,6],[11,2,5,14,5,6],[8,4,23,5,1,6],[9,15,4,7,13,6],[18,5,7,6,17,4]]
raw_2=np.random.randint(10, size=(6,6))
array_1=np.array(raw_1)
array_2=np.array(raw_2)
add=np.zeros((6,6))
multiply=np.zeros((6,6))


#### Function defining

In [327]:
def addMatrix(A,B):
    for i in range(len(A)):
        for j in range(len(A)):
            add[i][j] = A[i][j] + B[i][j]
    return print("addition using loops\n", add)

def multiMatrix(A, B):
    for i in range(len(A)):
        for j in range(len(A)):
            for k in range(len(B)):
                multiply[i][j] += A[i][k] * B[k][j]
    return print("multiplication using loops\n", multiply)
    
def invert_matrix(BC):
    n = len(BC)
    I=np.identity(n)
    indices = list(range(n))
    for fd in range(n):
        diagScaler = 1.0 / BC[fd][fd] 
        for j in range(n):
            BC[fd][j] *= diagScaler
            I[fd][j] *= diagScaler
        for i in indices[0:fd] + indices[fd+1:]: 
            ro_op = BC[i][fd]
            for j in range(n): 
                BC[i][j] = BC[i][j] - ro_op * BC[fd][j]
                I[i][j] = I[i][j] - ro_op * I[fd][j]
    return print("inverse of matrix using loops\n",I)

#### addition
- In addition we simply applied element by element loop in our looping process 

In [328]:
#using loops
start1=T.time()
addMatrix(raw_1, raw_2)
end1=T.time()

#using numpy
start2=T.time()
nadd=np.add(raw_1,raw_2)
end2=T.time()
print("addition using numpy\n", nadd)

addition using loops
 [[ 3.  8.  9. 12.  8.  8.]
 [10. 11.  7. 14.  9.  9.]
 [19.  3.  9. 22.  8. 10.]
 [ 9. 13. 25.  5.  4. 12.]
 [14. 20. 12. 12. 17.  6.]
 [20.  7.  7.  8. 22. 12.]]
addition using numpy
 [[ 3  8  9 12  8  8]
 [10 11  7 14  9  9]
 [19  3  9 22  8 10]
 [ 9 13 25  5  4 12]
 [14 20 12 12 17  6]
 [20  7  7  8 22 12]]


#### multiplication
- In looping process here we applied row wise an coloumn wise loops.

In [329]:
start3=T.time()
multiMatrix(raw_1,raw_2)
end3=T.time()

#using numpy
start4=T.time()
nmultiply=np.matmul(array_1,array_2)
end4=T.time()
print("multiplication using numpy\n",nmultiply)

multiplication using loops
 [[148. 122. 115. 149. 111. 143.]
 [132. 142. 123. 146. 115. 133.]
 [125. 205.  98. 146. 144. 180.]
 [246. 117. 130. 269. 150. 198.]
 [224. 201. 209. 259. 172. 169.]
 [221. 218. 201. 274. 191. 147.]]
multiplication using numpy
 [[148 122 115 149 111 143]
 [132 142 123 146 115 133]
 [125 205  98 146 144 180]
 [246 117 130 269 150 198]
 [224 201 209 259 172 169]
 [221 218 201 274 191 147]]


#### Inverse
- In inverse we applied jordan elimination and row operations simultaneously for matrix and a identity matrix.

In [330]:
#using numpy
start5=T.time()
ninv=np.linalg.inv(array_1)
end5=T.time()
print('inverse of matrix using numpy\n', ninv)

#using loops
start6=T.time()
invert_matrix(raw_1)
end6=T.time()

inverse of matrix using numpy
 [[-0.18370539  0.15332153  0.01117883  0.05758076 -0.05683061  0.02768231]
 [-0.04450448 -0.10257554  0.01893536  0.01683198  0.16075447 -0.07416269]
 [ 0.08687616 -0.17400727  0.0068838   0.014405    0.07553063 -0.01453247]
 [ 0.1501493  -0.36242443  0.13893615 -0.0668131   0.19324171 -0.07963443]
 [ 0.16863358 -0.13385665 -0.03054565 -0.06961762  0.02809416  0.05593826]
 [-0.2116451   0.85531264 -0.16460577  0.09073236 -0.4866467   0.12527886]]
inverse of matrix using loops
 [[-0.18370539  0.15332153  0.01117883  0.05758076 -0.05683061  0.02768231]
 [-0.04450448 -0.10257554  0.01893536  0.01683198  0.16075447 -0.07416269]
 [ 0.08687616 -0.17400727  0.0068838   0.014405    0.07553063 -0.01453247]
 [ 0.1501493  -0.36242443  0.13893615 -0.0668131   0.19324171 -0.07963443]
 [ 0.16863358 -0.13385665 -0.03054565 -0.06961762  0.02809416  0.05593826]
 [-0.2116451   0.85531264 -0.16460577  0.09073236 -0.4866467   0.12527886]]


In [331]:
print(f"""addition => loops time={end1-start1}, numpy time={end2-start2}
multiply => loops time={end3-start3}, numpy time={end4-start4}
inverse  => loops time={end6-start6}, numpy time={end5-start5}""")

addition => loops time=0.0008957386016845703, numpy time=8.368492126464844e-05
multiply => loops time=0.0007708072662353516, numpy time=4.792213439941406e-05
inverse  => loops time=0.0009338855743408203, numpy time=0.0002703666687011719


#### Conclusion
- As from above we can see that numpy does matrix operations faster than traditional looping process