To import the required libraries

In [28]:
import numpy as np
import random

to input the size of the matrix

In [29]:
n=input("Enter size of square matrix")
n=int(n)

Enter size of square matrix3


In [30]:
array1=[[random.random() for i in range(n)] for j in range(n)]
array2=[[random.random() for i in range(n)] for j in range(n)]

to print the first array

In [31]:
print("First array")
for e in array1:
    print(e)

First array
[0.03393607608682425, 0.5145299340873966, 0.17618332577950424]
[0.44244943296274664, 0.7194158551660006, 0.1410453939225349]
[0.03646158991663051, 0.5757838805525957, 0.6873650244260557]


to print the second array

In [32]:
print("Second array")
for e in array2:
    print(e)

Second array
[0.6484999146561545, 0.8541539966475761, 0.14025855104775187]
[0.6185634164929877, 0.806422676006187, 0.00723294810260533]
[0.0704197541215612, 0.7503224433523117, 0.8711013076111636]


To compute their product

In [33]:
productmat=np.zeros((n,n))
for i in range(len(array1)):
    #iterate through columns of array1
    for j in range(len(array2[0])):
        # iterate through rows of array2
        for k in range(len(array2)):
           productmat[i][j] += array1[i][k] * array2[k][j]

To print thier product now

In [34]:
print("Their product")
for r in productmat:
    print(r)

Their product
[0.35268372 0.57610954 0.16195492]
[0.74186513 1.06390274 0.19012564]
[0.42820826 1.0112144  0.60804324]


Now let's head on to the addition part

In [35]:
summat=np.zeros((n,n))
for i in range(n):
    for j in range(n):
        summat[i][j]=array1[i][j] + array2[i][j]


Now printing

In [36]:
print("Their sum")
for r in summat:
    print(r)

Their sum
[0.68243599 1.36868393 0.31644188]
[1.06101285 1.52583853 0.14827834]
[0.10688134 1.32610632 1.55846633]


Now the inverse part

In [37]:
def print_matrix(Title, M):
    print(Title)
    for row in M:
        print([round(x,3)+0 for x in row])
        
def print_matrices(Action, Title1, M1, Title2, M2):
    print(Action)
    print(Title1, '\t'*int(len(M1)/2)+"\t"*len(M1), Title2)
    for i in range(len(M1)):
        row1 = ['{0:+7.3f}'.format(x) for x in M1[i]]
        row2 = ['{0:+7.3f}'.format(x) for x in M2[i]]
        print(row1,'\t', row2)
        
def zeros_matrix(rows, cols):
    A = []
    for i in range(rows):
        A.append([])
        for j in range(cols):
            A[-1].append(0.0)

    return A

def copy_matrix(M):
    rows = len(M)
    cols = len(M[0])

    MC = zeros_matrix(rows, cols)

    for i in range(rows):
        for j in range(rows):
            MC[i][j] = M[i][j]

    return MC

def matrix_multiply(A,B):
    rowsA = len(A)
    colsA = len(A[0])

    rowsB = len(B)
    colsB = len(B[0])

    if colsA != rowsB:
        print('Number of A columns must equal number of B rows.')
        sys.exit()

    C = zeros_matrix(rowsA, colsB)

    for i in range(rowsA):
        for j in range(colsB):
            total = 0
            for ii in range(colsA):
                total += A[i][ii] * B[ii][j]
            C[i][j] = total

    return C

In [38]:
A = array1
I = [[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,0,1]]
print_matrix('A Matrix', A)
print()
print_matrix('I Matrix', I)

A Matrix
[0.034, 0.515, 0.176]
[0.442, 0.719, 0.141]
[0.036, 0.576, 0.687]

I Matrix
[1, 0, 0, 0, 0]
[0, 1, 0, 0, 0]
[0, 0, 1, 0, 0]
[0, 0, 0, 1, 0]
[0, 0, 0, 0, 1]


In [39]:
AM = copy_matrix(A)
IM = copy_matrix(I)
n = len(AM)

exString = """
Since the matrices won't be the original A and I as we start row operations, 
    the matrices will be called: AM for "A Morphing", and IM for "I Morphing" 
"""
print(exString)
print_matrix('AM Matrix', AM)
print()
print_matrix('IM Matrix', IM)


Since the matrices won't be the original A and I as we start row operations, 
    the matrices will be called: AM for "A Morphing", and IM for "I Morphing" 

AM Matrix
[0.034, 0.515, 0.176]
[0.442, 0.719, 0.141]
[0.036, 0.576, 0.687]

IM Matrix
[1, 0, 0, 0, 0]
[0, 1, 0, 0, 0]
[0, 0, 1, 0, 0]
[0, 0, 0, 1, 0]
[0, 0, 0, 0, 1]


In [40]:
fd = 0 # fd stands for focus diagonal
fdScaler = 1. / AM[fd][fd]

for j in range(n): # using j to indicate cycling through columns
    AM[fd][j] = fdScaler * AM[fd][j]
    IM[fd][j] = fdScaler * IM[fd][j]

print_matrix('AM Matrix', AM)
print()
print_matrix('IM Matrix', IM)

AM Matrix
[1.0, 15.162, 5.192]
[0.442, 0.719, 0.141]
[0.036, 0.576, 0.687]

IM Matrix
[29.467, 0.0, 0.0, 0, 0]
[0, 1, 0, 0, 0]
[0, 0, 1, 0, 0]
[0, 0, 0, 1, 0]
[0, 0, 0, 0, 1]


In [41]:
n = len(A)
indices = list(range(n))

for i in indices[0:fd] + indices[fd+1:]: # *** skip row with fd in it.
    crScaler = AM[i][fd] # cr stands for "current row".
    for j in range(n): # cr - crScaler * fdRow, but one element at a time.
        AM[i][j] = AM[i][j] - crScaler * AM[fd][j]
        IM[i][j] = IM[i][j] - crScaler * IM[fd][j]
    
print_matrix('AM Matrix', AM)
print()
print_matrix('IM Matrix', IM)

AM Matrix
[1.0, 15.162, 5.192]
[0.0, -5.989, -2.156]
[0.0, 0.023, 0.498]

IM Matrix
[29.467, 0.0, 0.0, 0, 0]
[-13.038, 1.0, 0.0, 0, 0]
[-1.074, 0.0, 1.0, 0, 0]
[0, 0, 0, 1, 0]
[0, 0, 0, 0, 1]


In [42]:
indices = list(range(n)) # to allow flexible row referencing ***
# We've already run for fd = 0, now let's run for fd = 1 to the last fd
for fd in range(1,n): # fd stands for focus diagonal
    fdScaler = 1.0 / AM[fd][fd]
    # FIRST: scale fd row with fd inverse. 
    for j in range(n): # Use j to indicate column looping.
        AM[fd][j] *= fdScaler
        IM[fd][j] *= fdScaler
    
    # Section to print out current actions:
    string1 = '\nUsing the matrices above, Scale row-{} of AM and IM by '
    string2 = 'diagonal element {} of AM, which is 1/{:+.3f}.\n'
    stringsum = string1 + string2
    val1 = fd+1; val2 = fd+1
    Action = stringsum.format(val1,val2,round(1./fdScaler,3))
    print(Action)
    print_matrix('AM Matrix', AM)
    print()
    print_matrix('IM Matrix', IM)
    print()
    
    # SECOND: operate on all rows except fd row.
    for i in indices[:fd] + indices[fd+1:]: # *** skip row with fd in it.
        crScaler = AM[i][fd] # cr stands for "current row".
        for j in range(n): # cr - crScaler * fdRow, but one element at a time.
            AM[i][j] = AM[i][j] - crScaler * AM[fd][j]
            IM[i][j] = IM[i][j] - crScaler * IM[fd][j]
        
        # Section to print out current actions:
        string1 = 'Using the matrices above, subtract {:+.3f} * row-{} of AM from row-{} of AM, and \n'
        string2 = '\tsubtract {:+.3f} * row-{} of IM from row-{} of IM\n'
        val1 = i+1; val2 = fd+1
        stringsum = string1 + string2
        Action = stringsum.format(crScaler, val2, val1, crScaler, val2, val1)
        print(Action)
        print_matrix('AM Matrix', AM)
        print()
        print_matrix('IM Matrix', IM)
        print()


Using the matrices above, Scale row-2 of AM and IM by diagonal element 2 of AM, which is 1/-5.989.

AM Matrix
[1.0, 15.162, 5.192]
[0.0, 1.0, 0.36]
[0.0, 0.023, 0.498]

IM Matrix
[29.467, 0.0, 0.0, 0, 0]
[2.177, -0.167, 0.0, 0, 0]
[-1.074, 0.0, 1.0, 0, 0]
[0, 0, 0, 1, 0]
[0, 0, 0, 0, 1]

Using the matrices above, subtract +15.162 * row-2 of AM from row-1 of AM, and 
	subtract +15.162 * row-2 of IM from row-1 of IM

AM Matrix
[1.0, 0.0, -0.267]
[0.0, 1.0, 0.36]
[0.0, 0.023, 0.498]

IM Matrix
[-3.54, 2.532, 0.0, 0, 0]
[2.177, -0.167, 0.0, 0, 0]
[-1.074, 0.0, 1.0, 0, 0]
[0, 0, 0, 1, 0]
[0, 0, 0, 0, 1]

Using the matrices above, subtract +0.023 * row-2 of AM from row-3 of AM, and 
	subtract +0.023 * row-2 of IM from row-3 of IM

AM Matrix
[1.0, 0.0, -0.267]
[0.0, 1.0, 0.36]
[0.0, 0.0, 0.49]

IM Matrix
[-3.54, 2.532, 0.0, 0, 0]
[2.177, -0.167, 0.0, 0, 0]
[-1.124, 0.004, 1.0, 0, 0]
[0, 0, 0, 1, 0]
[0, 0, 0, 0, 1]


Using the matrices above, Scale row-3 of AM and IM by diagonal element 3 of 