## Matrix multiplication

In [79]:
import numpy as np
import time
a=np.random.randint(2,10)
b=np.random.randint(2,10)
c=np.random.randint(2,10)
arr1=np.random.randn(a,b)
arr2=np.random.randn(b,c)
arr3=np.zeros([a,c])
time1=time.time()
for x in range(len(arr1)):
    for y in range(len(arr2[0])):
        for z in range(len(arr2)):
            arr3[x,y]+=arr1[x,z]*arr2[z,y]
print(arr3)
time2=time.time()
print(arr1.dot(arr2))
time3=time.time()
print(time2-time1)
print(time3-time2)

[[ 1.72862501 -0.87357299 -2.30843963 -3.80947199 -4.67891906 -0.91849856
  -0.29327499 -1.40466231]
 [-3.47589858 -1.00177375 -0.12853325  0.72032518 -0.17955708 -1.44096816
   0.96004682 -1.41491382]
 [-1.41474144  1.95828708 -0.11378742  4.10832912 -2.07050819  1.53926529
   1.67931522  0.38569457]
 [-1.98108887  2.85895132  8.18205275 -0.50762783 -1.22288863  5.22447422
   4.37344292  3.36562388]
 [-1.69072971  0.83431383  2.60236633  4.13907032  0.52841536  5.88940089
  -1.95963879  7.44000147]]
[[ 1.72862501 -0.87357299 -2.30843963 -3.80947199 -4.67891906 -0.91849856
  -0.29327499 -1.40466231]
 [-3.47589858 -1.00177375 -0.12853325  0.72032518 -0.17955708 -1.44096816
   0.96004682 -1.41491382]
 [-1.41474144  1.95828708 -0.11378742  4.10832912 -2.07050819  1.53926529
   1.67931522  0.38569457]
 [-1.98108887  2.85895132  8.18205275 -0.50762783 -1.22288863  5.22447422
   4.37344292  3.36562388]
 [-1.69072971  0.83431383  2.60236633  4.13907032  0.52841536  5.88940089
  -1.95963879  7

__we can see that the answer of matrix multiplication is the same but the time taken while using for loops(in the program made by me) is different__
## Matrix addition

In [80]:
arr6=np.zeros([a,b])
arr4=np.random.randn(a,b)
arr5=np.random.randn(a,b)
time1=time.time()
for x in range(len(arr4)):
    for y in range(len(arr4[0])):
        arr6[x,y]=arr4[x,y]+arr5[x,y]
print(arr6)
time2=time.time()
print(arr4+arr5)
time3=time.time()
print(time2-time1)
print(time3-time2)

[[ 0.47387634  0.19441506  2.48686662 -0.90881349 -0.74414446  1.55421616
  -1.62308011  0.15190669  0.84834032]
 [ 0.18772082  1.03551342  0.3072302  -0.1578325   1.14387697  1.16356319
   0.44033892  1.68727864  2.53150392]
 [ 1.16054998  3.66573195  1.11901814  0.2502173  -1.23223946  0.83819149
  -2.36928843 -0.66389987 -0.20164154]
 [ 0.09929065 -0.74396248  1.76348647  1.46389348  1.11947844 -2.22335452
   0.18990666 -0.18110937  0.22839275]
 [ 1.21286974 -0.2916647   2.57371307  0.56652674 -2.05172453  3.1834012
   0.1877398   0.53087799  2.24662959]]
[[ 0.47387634  0.19441506  2.48686662 -0.90881349 -0.74414446  1.55421616
  -1.62308011  0.15190669  0.84834032]
 [ 0.18772082  1.03551342  0.3072302  -0.1578325   1.14387697  1.16356319
   0.44033892  1.68727864  2.53150392]
 [ 1.16054998  3.66573195  1.11901814  0.2502173  -1.23223946  0.83819149
  -2.36928843 -0.66389987 -0.20164154]
 [ 0.09929065 -0.74396248  1.76348647  1.46389348  1.11947844 -2.22335452
   0.18990666 -0.18110

__again the python library is faster...__

## Inverse of a matrix

In [81]:
time1=time.time()
def smatrix(arr, x, y, n):
    ar=np.zeros([n-1,n-1])
    for i in range(n):
        for j in range(n):
            if (i==x or j==y):
                continue
            elif j<y and i<x:
                ar[i][j]=arr[i][j]
            elif j>y and i>x:
                ar[i-1][j-1]=arr[i][j]
            elif j>y and i<x:
                ar[i][j-1]=arr[i][j]
            elif j<y and i>x:
                ar[i-1][j]=arr[i][j]
    return ar

def determinant(arr):
    if len(arr)==2:
        return arr[0][0]*arr[1][1]-arr[0][1]*arr[1][0]
    det=0
    for x in range(len(arr)):
        det+=((-1)**x)*arr[0][x]*determinant(smatrix(arr,0, x,len(arr)))
    return det

arr=np.random.randn(a,a)
arans=np.zeros([a,a])
detarr=determinant(arr)
if detarr==0:
    print("determinant is zero hence inverse not possible")
for x in range(a):
    for y in range(a):
        arans[y][x]=((-1)^(x+y))*determinant(smatrix(arr, x, y, a))/detarr
        arans[y][x]/=x+y+1
        if (x+y)%2 == 0:
            arans[y][x]*=-1
detarans=determinant(arans)
print(detarans)
print(detarr)
print(arr)
print(arans)
time2=time.time()
print(np.linalg.inv(arr))
time3=time.time()
print(time2-time1)
print(time3-time2)

-1.2899993313252525
-0.775194200273477
[[-1.53002884e-01  9.74150063e-01  2.48324085e-01 -1.25840279e-01
   2.95806326e-01]
 [ 9.95197376e-01 -1.13455776e+00  5.76649018e-02 -8.45503088e-01
   1.07867277e+00]
 [-1.29479851e+00  2.09533110e+00  2.04928033e-03  1.99605918e-01
  -6.12852692e-01]
 [-3.42124353e-02  9.98330234e-01  1.24403642e+00 -6.66248065e-01
   1.34447775e+00]
 [-5.25437175e-02  1.42133307e+00  1.06167098e-01  6.55371380e-01
   1.16486187e+00]]
[[ 4.71390593 -0.82601811 -1.92321872 -0.86107853 -0.45013818]
 [ 2.26729926 -0.17640995 -0.38736403 -0.43391767 -0.11537617]
 [ 0.61007034 -1.28484653 -1.06302323  0.77956605 -0.42418726]
 [-0.45490646 -0.94856836 -0.69887006  0.09149543  0.52061203]
 [-2.35353055  0.82877484  0.87598178  0.36808614  0.72470098]]
[[ 4.71390593 -0.82601811 -1.92321872 -0.86107853 -0.45013818]
 [ 2.26729926 -0.17640995 -0.38736403 -0.43391767 -0.11537617]
 [ 0.61007034 -1.28484653 -1.06302323  0.77956605 -0.42418726]
 [-0.45490646 -0.94856836 -0.6

__Inverse of the matrix code by me and by using library__