## Matrix multiplication

In [4]:
import numpy as np
import time
# taking size of matrices
a=np.random.randint(2,10)
b=np.random.randint(2,10)
c=np.random.randint(2,10)
#making random matrices
arr1=np.random.randn(a,b)
arr2=np.random.randn(b,c)
arr3=np.zeros([a,c])
#marking initial time
time1=time.time()
#multiplying the arrays 1 and 2 and storing the result in array 3
for x in range(len(arr1)):
    for y in range(len(arr2[0])):
        for z in range(len(arr2)):
            arr3[x,y]+=arr1[x,z]*arr2[z,y]
print(arr3)
time2=time.time() #end of my program time = start of the library program
print(arr1.dot(arr2)) #multiplication
time3=time.time() #end of library program
print(time2-time1)
print(time3-time2)

[[-1.78330038  1.10701997 -1.61212403 -1.82811242]
 [-0.83031566  1.02842111 -1.94003294 -1.47632915]
 [-0.68474145  3.13312869 -2.4505439   7.77455468]
 [ 0.36116809  0.47292524  1.72412946  1.55124332]
 [-1.5210136  -0.33838859 -1.17463561  0.86724673]
 [ 0.25087153  0.80410249 -2.44518157  3.78188308]
 [-0.42895389  2.54073424 -0.96163635 -0.94326397]
 [-2.32557582 -1.72784606 -3.27702259  1.02233174]]
[[-1.78330038  1.10701997 -1.61212403 -1.82811242]
 [-0.83031566  1.02842111 -1.94003294 -1.47632915]
 [-0.68474145  3.13312869 -2.4505439   7.77455468]
 [ 0.36116809  0.47292524  1.72412946  1.55124332]
 [-1.5210136  -0.33838859 -1.17463561  0.86724673]
 [ 0.25087153  0.80410249 -2.44518157  3.78188308]
 [-0.42895389  2.54073424 -0.96163635 -0.94326397]
 [-2.32557582 -1.72784606 -3.27702259  1.02233174]]
0.003694772720336914
0.0004978179931640625


__we can see that the answer of matrix multiplication is the same but the time taken while using for loops(in the program made by me) is different__
## Matrix addition

In [5]:
#few more random arrays for addition
arr6=np.zeros([a,b])
arr4=np.random.randn(a,b)
arr5=np.random.randn(a,b)
time1=time.time() # start time
#matrix summation
for x in range(len(arr4)):
    for y in range(len(arr4[0])):
        arr6[x,y]=arr4[x,y]+arr5[x,y]
print(arr6)
time2=time.time() #end time 1 
print(arr4+arr5)
time3=time.time() #end time 2
print(time2-time1)
print(time3-time2)

[[-0.42287577  0.72534535 -0.27223143 -0.3401773   1.68833301  2.68560732
   0.41251828]
 [ 0.33462229 -1.64823849  1.50452137 -2.90608023 -1.46070239 -2.30319468
   1.26477882]
 [-2.30479802 -0.77016042 -2.03258564  0.52050292  0.55655997  0.9350291
  -0.14736067]
 [ 0.7989316   2.50350101 -0.28741673 -1.15082716  1.05683478 -3.29163067
  -3.45421311]
 [ 0.41057917 -1.82411326  1.96843921 -1.13914727 -0.10219048 -0.17359119
   0.86233048]
 [-2.73623778  0.0834465   1.27772463 -0.25666306 -0.99917572  0.87133862
   1.06697562]
 [ 0.76328434 -0.72100159 -0.03465862 -0.48693282 -0.32658774  3.81202067
   0.21795597]
 [ 2.14215385  0.41304037 -2.98155089 -0.71855639  2.72515241  0.98572588
  -2.64103968]]
[[-0.42287577  0.72534535 -0.27223143 -0.3401773   1.68833301  2.68560732
   0.41251828]
 [ 0.33462229 -1.64823849  1.50452137 -2.90608023 -1.46070239 -2.30319468
   1.26477882]
 [-2.30479802 -0.77016042 -2.03258564  0.52050292  0.55655997  0.9350291
  -0.14736067]
 [ 0.7989316   2.50350

## Inverse of a matrix

In [6]:
time1=time.time()
def smatrix(arr, x, y, n): #returns the matrix we get on removing the row and column x,y resp.
    ar=np.zeros([n-1,n-1])
    for i in range(n):
        for j in range(n):
            if (i==x or j==y):
                continue
            elif j<y and i<x:
                ar[i][j]=arr[i][j]
            elif j>y and i>x:
                ar[i-1][j-1]=arr[i][j]
            elif j>y and i<x:
                ar[i][j-1]=arr[i][j]
            elif j<y and i>x:
                ar[i-1][j]=arr[i][j]
    return ar

def determinant(arr): #for getting determinant of the matrix using recursion
    if len(arr)==2:
        return arr[0][0]*arr[1][1]-arr[0][1]*arr[1][0]
    det=0
    for x in range(len(arr)):
        det+=((-1)**x)*arr[0][x]*determinant(smatrix(arr,0, x,len(arr)))
    return det

arr=np.random.randn(a,a)
arans=np.zeros([a,a])
detarr=determinant(arr)
if detarr==0:
    print("determinant is zero hence inverse not possible")
#making the program for finding cofactors and storing them in appropriate places for adjecent matrix and dividing the value by determinant to get ht eentries in inverse of the matrix
for x in range(a):
    for y in range(a):
        arans[y][x]=((-1)^(x+y))*determinant(smatrix(arr, x, y, a))/detarr
        arans[y][x]/=x+y+1
        if (x+y)%2 == 0:
            arans[y][x]*=-1
detarans=determinant(arans)
print(detarans)
print(detarr)
print(arr)
print(arans)
time2=time.time()
print(np.linalg.inv(arr)) #returns inverse of the inputted matrix
time3=time.time()
print(time2-time1)
print(time3-time2)

-0.02160635919439193
-46.28267034732801
[[ 2.25514891 -2.00204981 -0.31460591 -2.1817209  -2.24767181  1.06311104
   1.63633601 -0.43050527]
 [ 0.03636319  0.18794092  0.40630479 -0.13732516  0.05695292  0.68886502
   0.23844375 -1.05537683]
 [-1.62613391 -0.82149053 -1.68596729 -0.12871124  0.30398223  0.47370414
   0.38899436 -1.31213249]
 [-0.15607085  0.10892597 -0.38785982  0.79292148 -0.75447689 -0.00863001
   0.41589633 -0.17447449]
 [-1.17964269  1.21776666  0.24031573  1.41527309 -0.27168976 -0.87175525
   0.47321361  0.1406582 ]
 [ 0.32539335 -0.14447597 -0.14861141 -1.00095917 -1.44183922 -1.61657767
   0.53604093 -2.20107549]
 [ 1.13628996 -1.67720991  2.09327793  1.24398843  1.34925052 -0.75072162
   0.80758646  0.90101235]
 [ 0.15191583 -0.56671755 -0.68922345 -1.64362475  0.43567944 -0.31534823
  -0.1894269   1.11747214]]
[[-0.79867681  2.16229246 -0.75009412  3.79397821 -1.15333423  0.2664687
   0.32174577  1.85666829]
 [-0.5466582   1.94297139 -0.58980841  2.34928855 -