## Matrix multiplication

In [6]:
import numpy as np
import time
a=np.random.randint(2,10)
b=np.random.randint(2,10)
c=np.random.randint(2,10)
arr1=np.random.randn(a,b)
arr2=np.random.randn(b,c)
arr3=np.zeros([a,c])
time1=time.time()
for x in range(len(arr1)):
    for y in range(len(arr2[0])):
        for z in range(len(arr2)):
            arr3[x,y]+=arr1[x,z]*arr2[z,y]
print(arr3)
time2=time.time()
print(arr1.dot(arr2))
time3=time.time()
print(time2-time1)
print(time3-time2)

[[-1.39719244 -0.05115749  0.76482893]
 [ 1.54035387  3.48419727 -0.60267569]
 [-0.20444204  0.42651561  1.35380659]
 [ 0.31925476  1.4751721   0.68476113]
 [-0.12237532  3.16613267 -2.28266115]
 [ 3.65779293  3.37139457  7.65560829]
 [-1.23309355  0.17953712  3.3933209 ]
 [ 0.31638703 -1.46532683 -2.95373537]]
[[-1.39719244 -0.05115749  0.76482893]
 [ 1.54035387  3.48419727 -0.60267569]
 [-0.20444204  0.42651561  1.35380659]
 [ 0.31925476  1.4751721   0.68476113]
 [-0.12237532  3.16613267 -2.28266115]
 [ 3.65779293  3.37139457  7.65560829]
 [-1.23309355  0.17953712  3.3933209 ]
 [ 0.31638703 -1.46532683 -2.95373537]]
0.008005857467651367
0.010622739791870117


__we can see that the answer of matrix multiplication is the same but the time taken while using for loops(in the program made by me) is different__
## Matrix addition

In [9]:
arr6=np.zeros([a,b])
arr4=np.random.randn(a,b)
arr5=np.random.randn(a,b)
time1=time.time()
for x in range(len(arr4)):
    for y in range(len(arr4[0])):
        arr6[x,y]=arr4[x,y]+arr5[x,y]
print(arr6)
time2=time.time()
print(arr4+arr5)
time3=time.time()
print(time2-time1)
print(time3-time2)

[[ 1.10853369 -1.43972908 -0.97313072 -1.77665969 -1.52596417  1.96087921
   0.83591139]
 [ 1.38611154  1.18871643  0.64832971  1.37528043  2.12095157 -1.42341899
  -1.38760478]
 [-1.41635918  1.07803804 -1.37658825 -2.5870864  -2.7225311   0.1282821
   0.91726077]
 [-2.03019354 -2.2012646  -1.38984138 -0.79947981 -0.92494588 -0.71733892
   3.02579604]
 [ 1.20895183  1.0049079   1.08623244 -0.08183679 -1.9154841  -1.4698856
  -0.51347988]
 [ 1.26020469 -1.56052494 -0.12696309 -1.02815661 -1.03580488 -0.74238854
   2.25995454]
 [-1.0804431   1.07766513 -1.32465255 -0.19001691 -0.34139207  0.83801371
  -0.11907718]
 [ 0.32373853  1.32895747 -0.51389923 -1.29504998 -2.35651417 -0.03766856
  -0.75662578]]
[[ 1.10853369 -1.43972908 -0.97313072 -1.77665969 -1.52596417  1.96087921
   0.83591139]
 [ 1.38611154  1.18871643  0.64832971  1.37528043  2.12095157 -1.42341899
  -1.38760478]
 [-1.41635918  1.07803804 -1.37658825 -2.5870864  -2.7225311   0.1282821
   0.91726077]
 [-2.03019354 -2.201264

__again the python library is faster...__

## Inverse of a matrix

In [18]:
time1=time.time()
def smatrix(arr, x, y, n):
    ar=np.zeros([n-1,n-1])
    for i in range(n):
        for j in range(n):
            if (i==x or j==y):
                continue
            elif j<y and i<x:
                ar[i][j]=arr[i][j]
            elif j>y and i>x:
                ar[i-1][j-1]=arr[i][j]
            elif j>y and i<x:
                ar[i][j-1]=arr[i][j]
            elif j<y and i>x:
                ar[i-1][j]=arr[i][j]
    return ar

def determinant(arr):
    if len(arr)==2:
        return arr[0][0]*arr[1][1]-arr[0][1]*arr[1][0]
    det=0
    for x in range(len(arr)):
        det+=((-1)**x)*arr[0][x]*determinant(smatrix(arr,0, x,len(arr)))
    return det

arr=np.random.randn(a,a)
arans=np.zeros([a,a])
detarr=determinant(arr)
for x in range(a):
    for y in range(a):
        arans[x][y]=((-1)^(x+y))*determinant(smatrix(arr, x, y, a))/detarr
print(arr)
print(arans)
time2=time.time()
print(np.linalg.inv(arr))
time3=time.time()
print(time2-time1)
print(time3-time2)

[[-0.50857514 -0.6613841  -0.48012167  0.66231185  0.53419884 -0.42271074
   0.69472849 -1.19914859]
 [ 1.95420144 -2.03104828 -0.57534934  0.72777103 -0.99836947 -1.40674508
  -1.00619612  2.60967755]
 [ 0.29957845 -0.42181358  0.13517936  1.08886785 -1.10332864  1.12822331
  -0.93346362  1.24625524]
 [-2.33267119 -0.05048531  0.77864832 -0.6113958  -0.20329908  0.21213198
   1.41035461  2.27942236]
 [ 0.80490138  1.58019959 -0.08320019 -0.20707596 -1.1915703   0.02137288
  -0.17228134 -1.2919095 ]
 [ 0.72845775  0.40759415  0.6792678  -0.37862914 -2.05145835  0.25876419
  -1.5176374   0.33424786]
 [ 0.97072003 -0.35590479 -0.03413202 -0.79598283 -1.09764457  2.08308516
  -0.76158887 -0.24972014]
 [ 1.05377509  0.66544956  1.19021437  1.98576775  1.4642375   0.92309689
  -1.13193042 -0.62364126]]
[[-0.06341575 -1.1991787  -1.93206179  1.25716622  2.18356999 -0.50229919
  -3.88061726 -3.6659806 ]
 [ 0.81378507  0.52575497  1.1932708  -0.27280382 -0.70264389  0.65222175
   3.39216899 -0

__Inverse of the matrix code by me and by using library__