In [86]:
import time as T
import numpy as np
V =[[1,5,9,7,5],[4,9,2,7,7],[11,2,5,14,5],[8,4,23,5,1],[9,15,4,7,13]]
R =np.random.randint(10, size=(5,5))
K =np.array(V)
M =np.array(R)
add=np.zeros((5,5))
multiply=np.zeros((5,5))

In [87]:
A = V 
B = R




    

def invert_matrix(A):
    n = len(A)
    I=np.identity(n) #creates a identity matrix of order n
    index = list(range(n))
    for fd in range(n):
        diagScaler = 1.0 / A[fd][fd] 
        for j in range(n):
            A[fd][j] *= diagScaler
            I[fd][j] *= diagScaler
        for i in index[0:fd] + index[fd+1:]: 
            ro_op = A[i][fd]
            for j in range(n): 
                A[i][j] = A[i][j] - ro_op * A[fd][j]
                I[i][j] = I[i][j] - ro_op * I[fd][j]
    return print("inverse using loops\n",I)


In [88]:

#using loops
start1=T.time()
for i in range(len(A)):        
    for j in range(len(A)):
        add[i][j] = A[i][j] + B[i][j]
print("addition using loops\n""",add)
print(f"""addition => loops time={end1-start1}""")





addition using loops
 [[ 9.  8. 14.  7.  5.]
 [ 8.  9.  2. 10.  8.]
 [16. 11.  9. 14.  8.]
 [ 9.  6. 28.  7.  6.]
 [15. 22. 11. 11. 13.]]
addition => loops time=-1522.1828994750977


In [89]:

#using numpy
start2=T.time()
nadd=np.add(V,R)
end2=T.time()
print("addition using numpy\n", nadd)
print(f""" numpy time={end2-start2}""")



addition using numpy
 [[ 9  8 14  7  5]
 [ 8  9  2 10  8]
 [16 11  9 14  8]
 [ 9  6 28  7  6]
 [15 22 11 11 13]]
 numpy time=0.00025916099548339844


In [90]:
start3=T.time()
for i in range(len(A)):
    for j in range(len(A)):
        for k in range(len(B)):
            multiply[i][j] += A[i][k] * B[k][j]
print("multiplication using loops\n", multiply)

end3=T.time()
print(f"""multiply => loops time={end3-start3}""")


multiplication using loops
 [[110. 133. 111.  49.  67.]
 [127.  93. 112.  69.  50.]
 [165. 141. 180.  54.  87.]
 [206. 248. 164.  26.  98.]
 [237. 168. 187. 111.  62.]]
multiply => loops time=0.0028350353240966797


In [91]:

#using numpy
start4=T.time()
nmultiply=np.matmul(K,M)
end4=T.time()
print("multiplication using numpy\n",nmultiply)
print(f""" numpy time={end4-start4}""")

multiplication using numpy
 [[110 133 111  49  67]
 [127  93 112  69  50]
 [165 141 180  54  87]
 [206 248 164  26  98]
 [237 168 187 111  62]]
 numpy time=0.00020384788513183594


In [92]:

#using numpy
start5=T.time()
ninv=np.linalg.inv(K)
end5=T.time()
print('inverse of matrix using numpy\n', ninv)
print(f"""numpy time={end5-start5}""")

inverse of matrix using numpy
 [[-0.13693912 -0.03567305  0.04755102  0.03753204  0.05070152]
 [-0.16979434  0.4037532  -0.07850811  0.0705438  -0.12733108]
 [ 0.06232511 -0.07479013 -0.01221063  0.02493004  0.01907911]
 [ 0.01561552  0.18126137  0.03430327 -0.00913841 -0.11609886]
 [ 0.26313524 -0.51576228  0.04295247 -0.11013052  0.24538677]]
numpy time=0.0015230178833007812


In [93]:

#using loops
start6=T.time()
invert_matrix(V)
end6=T.time()

print(f"""inverse  => loops time={end6-start6}""")

inverse using loops
 [[-0.13693912 -0.03567305  0.04755102  0.03753204  0.05070152]
 [-0.16979434  0.4037532  -0.07850811  0.0705438  -0.12733108]
 [ 0.06232511 -0.07479013 -0.01221063  0.02493004  0.01907911]
 [ 0.01561552  0.18126137  0.03430327 -0.00913841 -0.11609886]
 [ 0.26313524 -0.51576228  0.04295247 -0.11013052  0.24538677]]
inverse  => loops time=0.00717616081237793
