In [2]:
import numpy as np
from numpy import random

x= random.randint(100)
y=random.randint(100)
m1=random.randint(100, size=(x,y))
m2=random.randint(100, size=(x,y))


[ 3  5  7  9 11]


# MATRIX ADDITION USING NUMPY 

In [11]:
import numpy as np
from numpy import random

x= random.randint(100)
y=random.randint(100)
m1=random.randint(100, size=(x,y))
m2=random.randint(100, size=(x,y))
add_matrix=np.add(m1,m2)
print(add_matrix)

[[164 111 113 ...  54  99  73]
 [144  47 106 ... 113  14  43]
 [150 126  98 ... 147  92 145]
 ...
 [ 40 150 130 ...  46 101  59]
 [108  93  67 ... 136  81 100]
 [172  78 125 ...  99  80  29]]


# MATRIX ADDITION WITHOUT USING NUMPY

In [1]:
import numpy as np
from numpy import random

x= random.randint(100)
y=random.randint(100)
m1=random.randint(100, size=(x,y))
m2=random.randint(100, size=(x,y))


add_matrix=random.randint(1, size=(x,y))
for i in range(x):
    for j in range(y):
        add_matrix[i][j]=m1[i][j]+m2[i][j]
print(add_matrix)

ModuleNotFoundError: No module named 'numpy'