In [8]:
from numpy import random
import numpy as np


In [9]:
m = random.randint(100)
n = random.randint(100)
x = random.randint(100, size=(m,n))
y = random.randint(100, size=(m,n))


In [10]:
#Without using numpy
mat_add = random.randint(1, size=(m,n))
for i in range(m):
   for j in range(n):
       mat_add[i][j] = x[i][j] + y[i][j]
print(mat_add)

[[143  72 135 ...  93  48  11]
 [161  99 123 ... 118 142  69]
 [139  65  64 ...  97 139 180]
 ...
 [181  97  75 ...  47 109  43]
 [108  15  93 ... 190  57 150]
 [106  43 100 ...  45  70 118]]


In [11]:
#Using numpy
ans = np.add(x,y)
print(ans)

[[143  72 135 ...  93  48  11]
 [161  99 123 ... 118 142  69]
 [139  65  64 ...  97 139 180]
 ...
 [181  97  75 ...  47 109  43]
 [108  15  93 ... 190  57 150]
 [106  43 100 ...  45  70 118]]
