In [1]:
import numpy as np
def matrix_op(n,mat1,mat2,operation):
    mat1 = np.random.randint(20,size=(n,n))
    mat2 = np.random.randint(20,size=(n,n))
    
    matrix3 = [[0 for x in range(n)] for y in range(n)] 
    i = 0
    j = 0
    k = 0
    if operation == "+" or operation == "-":
     for i in range(len(mat1)):
        for j in range(len(mat1[0])):
            if operation == "+":
              matrix3[i][j] = mat1[i][j] + mat2[i][j]
            elif operation == "-":
              matrix3[i][j] = mat1[i][j] - mat2[i][j]
    elif operation == "*":
     for i in range(len(mat1)):
        for j in range(len(mat2[0])):
            for k in range(len(mat2)):
                matrix3[i][j] += mat1[i][k]*mat2[k][j] 
      
           
    print(mat1)
    print(mat2)
    print(matrix3)
n = int(input())
matrix1 = np.random.randint(20,size=(n,n))
matrix2 = np.random.randint(20,size=(n,n))

operation = input("Enter the operation: ")
matrix_op(n,matrix1,matrix2,operation)
      


[[ 9  5  3]
 [12  7  7]
 [ 0  4 11]]
[[ 0 13  1]
 [17  8 16]
 [13 17 11]]
[[124, 208, 122], [210, 331, 201], [211, 219, 185]]
