In [1]:
#inverse of matrix
import numpy as np
def getCofactor(mat,temp,k,l,n):
  i = 0 
  j = 0
  row = 0
  col = 0
  for row in range(len(mat)):
      for col in range(len(mat[0])):
       if row != k and col != l:
           temp[i][j] = mat[row][col]
           j= j+1
           if j == len(mat)-1:
              j = 0
              i = i+1
def determinant(mat,n):
    Det = 0
    if n == 1:
      return mat[0][0]
    else:
        temp = [[0 for x in range(n)] for y in range(n)]
        sign = 1
        f = 0
        for f in range(n):
            getCofactor(mat,temp,0,f,n)
            Det += sign*mat[0][f]*determinant(temp,n-1)
            sign = - sign

    return Det
def adjoint_fn(mat,adjoint,n):
    if n == 1:
        adjoint[0][0] = 1
    sign = 1
    temp = [[0 for x in range(n)] for y in range(n)]  
    i = 0
    j = 0
    for i in range(n):
        for  j in range(n):
            getCofactor(mat,temp,i,j,n)
            if (i+j)%2 == 0:
             sign = 1
            else: 
             sign = -1
            
            adjoint[j][i] = (sign)*(determinant(temp,n-1))

def inverse_fn(mat,inverse,n):
    det = determinant(mat,n)

    if det == 0:
        print("Inverse doesn't exist")

    else:
        adjoint = [[0 for x in range(n)] for y in range(n)]
        adjoint_fn(mat,adjoint,n)
        i=0
        j=0
        for i in range(n):
            for j in range(n):
                inverse[i][j] = adjoint[i][j]/det

n = int(input("Order of matrix: "))
mat = np.random.randint(100,size=(n,n))
adjoint = [[0 for x in range(n)] for y in range(n)]
inverse = [[0 for x in range(n)] for y in range(n)]
inverse_fn(mat,inverse,n)
print(mat) 
print(inverse)



[[23 59 17 20]
 [ 3 18 75 98]
 [12 53 69 50]
 [10 88 67  0]]
[[-0.014610418941276982, -0.11180758280872108, 0.2249870298816041, -0.10283819745037155], [0.024921985705768025, 0.042762673935095204, -0.0937836351950938, 0.042390992930317554], [-0.030552694816340542, -0.0394782011671816, 0.08959835221421215, -0.025403364229316855], [0.01925191454434232, 0.03598530311360275, -0.05823195992039832, 0.014803357518409825]]
